apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ddo-orchestrator-monitor
  namespace: ddo-system
labels:
  release: prometheus
spec:
  selector:
    matchLabels:
      app: ddo-orchestrator
  endpoints:
    - port: http
      interval: 30s
