apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ddo-gateway
  namespace: ddo-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "ddo.example.com"
