name: Sync Issues from Markdown

on:
  push:
    branches: [main]
    paths: ['.github/ISSUE_TEMPLATES/**']

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Python Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install requests
          python scripts/sync_issues.py
